"""Adiciona tabela bot atualizado

Revision ID: 26326ccf14c3
Revises: a687abb1a4e3
Create Date: 2026-01-27 10:13:32.501787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26326ccf14c3'
down_revision = 'a687abb1a4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_menu_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('open_desk_ticket', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('response_message', sa.Text(), nullable=True))
        batch_op.alter_column('digit',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('queue_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.create_foreign_key(None, 'bot_menu_options', ['parent_id'], ['id'])

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_menu_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bot_menu_options', ['current_menu_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_menu_id')

    with op.batch_alter_table('bot_menu_options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('queue_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('digit',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)
        batch_op.drop_column('response_message')
        batch_op.drop_column('open_desk_ticket')
        batch_op.drop_column('description')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
