"""Adiciona tabela bot

Revision ID: 3e8a5782a590
Revises: f7f351a7e4aa
Create Date: 2026-01-26 11:50:54.597301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8a5782a590'
down_revision = 'f7f351a7e4aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_menu_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('digit', sa.String(length=2), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('queue_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_special_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=50), nullable=False),
    sa.Column('queue_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_queues',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('queue_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'queue_id')
    )
    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('failover_number', sa.String(length=20), nullable=True))

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_protocol', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('external_protocol')

    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.drop_column('failover_number')
        batch_op.drop_column('priority')

    op.drop_table('user_queues')
    op.drop_table('bot_special_rules')
    op.drop_table('bot_menu_options')
    # ### end Alembic commands ###
