"""Adiciona tabela faltantes5

Revision ID: a687abb1a4e3
Revises: a912dee07e66
Create Date: 2026-01-27 08:14:58.631639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a687abb1a4e3'
down_revision = 'a912dee07e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_menu_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generate_protocol', sa.Boolean(), nullable=True))

    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failover_numbers', sa.Text(), nullable=True))
        batch_op.drop_column('priority')
        batch_op.drop_column('failover_number')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failover_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('failover_numbers')

    with op.batch_alter_table('bot_menu_options', schema=None) as batch_op:
        batch_op.drop_column('generate_protocol')

    # ### end Alembic commands ###
