"""Adiciona tabela faltantes2

Revision ID: a912dee07e66
Revises: 3e8a5782a590
Create Date: 2026-01-26 12:47:19.048661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a912dee07e66'
down_revision = '3e8a5782a590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failover_queue_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'queues', ['failover_queue_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('failover_queue_id')

    # ### end Alembic commands ###
