"""Adiciona tabela botvip

Revision ID: c4325aed7361
Revises: 26326ccf14c3
Create Date: 2026-01-27 12:02:16.436268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4325aed7361'
down_revision = '26326ccf14c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_special_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_menu_id', sa.Integer(), nullable=True))
        batch_op.alter_column('queue_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.create_foreign_key(None, 'bot_menu_options', ['special_menu_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_special_rules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('queue_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('special_menu_id')

    # ### end Alembic commands ###
