"""Adiciona tabela botvip2

Revision ID: d266e4c2bc9a
Revises: c4325aed7361
Create Date: 2026-01-27 12:50:29.914793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd266e4c2bc9a'
down_revision = 'c4325aed7361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_menu_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vip_only', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_menu_options', schema=None) as batch_op:
        batch_op.drop_column('is_vip_only')

    # ### end Alembic commands ###
